import kenk.springdroolsexample.model.PersonRelated
import kenk.springdroolsexample.model.Person
import kenk.springdroolsexample.model.Monitoring
/*
rule "Is of valid age"
when
  Applicant(age < 18)
  $a : Application()
then
  $a.setValid(false);
  System.out.println("trigger rule Is of valid age");
end

rule "Application was made this year"
when
  $a : Application(dateApplied > "01-jan-2009")
then
  $a.setValid(false);
  System.out.println("Application was made this year");
end
*/

rule "Person age"
when
  Monitoring()
  $p: Person(age > 10)
then
  insert(new PersonRelated($p));
  System.out.println("insert test1");
end

rule "PersonRelated"
when
  PersonRelated()
then
  //insert(new Applicant("test1", 2));
  System.out.println("personal related");
end

rule "not PersonRelated"
when
  not PersonRelated()
then
  //insert(new Applicant("test1", 2));
  System.out.println("not personal related");
end

rule "jump go"
when
  $p: Person(age > 10)
  if (age > 18)do[large18]
  if(age > 100)break[large100]
then
  System.out.println("then jump go");
then[large18]
  System.out.println("larger than 18");
then[large100]
  System.out.println("larger than 100");
end
